# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.11
# Le loader 0.16.10 est très stable pour la 1.21.x
loader_version=0.16.10
# Loom 1.7 est recommandé pour la stabilité sur GitHub Actions
loom_version=1.7-SNAPSHOT

# Mod Properties
mod_version=1.0.0
# ATTENTION : Doit correspondre au package de tes fichiers Java
maven_group=com.tonnom.mod
# C'est le nom du fichier .jar final
archives_base_name=offhand-only

# Dependencies (Fabric API pour 1.21.11)
fabric_version=0.116.9+1.21.11