# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.11
# C'est cette ligne qui manquait ou était mal nommée :
yarn_mappings=1.21.1+build.3
loader_version=0.16.10

mod_version=1.0.0
maven_group=com.thomjap.mod
archives_base_name=offhand-only

# Ajoute celle-ci aussi pour être sûr
fabric_version=0.116.9+1.21.11